//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace HeroBash.HighScoresService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Score", Namespace="http://schemas.datacontract.org/2004/07/HighScoresService", IsReference=true)]
    public partial class Score : HighScoresService.EntityObject {
        
        private System.Nullable<System.DateTime> DateSubmittedField;
        
        private System.Nullable<decimal> DecimalScoreField;
        
        private System.Nullable<int> ExtraIntField;
        
        private string ExtraStringField;
        
        private System.Nullable<double> FloatScoreField;
        
        private int GameIDField;
        
        private System.Nullable<int> IntScoreField;
        
        private string PlayerNameField;
        
        private System.Nullable<int> RankField;
        
        private int ScoreIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSubmitted {
            get {
                return this.DateSubmittedField;
            }
            set {
                if ((this.DateSubmittedField.Equals(value) != true)) {
                    this.DateSubmittedField = value;
                    this.RaisePropertyChanged("DateSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DecimalScore {
            get {
                return this.DecimalScoreField;
            }
            set {
                if ((this.DecimalScoreField.Equals(value) != true)) {
                    this.DecimalScoreField = value;
                    this.RaisePropertyChanged("DecimalScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ExtraInt {
            get {
                return this.ExtraIntField;
            }
            set {
                if ((this.ExtraIntField.Equals(value) != true)) {
                    this.ExtraIntField = value;
                    this.RaisePropertyChanged("ExtraInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraString {
            get {
                return this.ExtraStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraStringField, value) != true)) {
                    this.ExtraStringField = value;
                    this.RaisePropertyChanged("ExtraString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> FloatScore {
            get {
                return this.FloatScoreField;
            }
            set {
                if ((this.FloatScoreField.Equals(value) != true)) {
                    this.FloatScoreField = value;
                    this.RaisePropertyChanged("FloatScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID {
            get {
                return this.GameIDField;
            }
            set {
                if ((this.GameIDField.Equals(value) != true)) {
                    this.GameIDField = value;
                    this.RaisePropertyChanged("GameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IntScore {
            get {
                return this.IntScoreField;
            }
            set {
                if ((this.IntScoreField.Equals(value) != true)) {
                    this.IntScoreField = value;
                    this.RaisePropertyChanged("IntScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScoreID {
            get {
                return this.ScoreIDField;
            }
            set {
                if ((this.ScoreIDField.Equals(value) != true)) {
                    this.ScoreIDField = value;
                    this.RaisePropertyChanged("ScoreID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.WeeklyScore))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.LastWeek))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.Score))]
    public partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.WeeklyScore))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.LastWeek))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.Score))]
    public partial class EntityObject : HighScoresService.StructuralObject {
        
        private HighScoresService.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HighScoresService.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeeklyScore", Namespace="http://schemas.datacontract.org/2004/07/HighScoresService", IsReference=true)]
    public partial class WeeklyScore : HighScoresService.EntityObject {
        
        private System.Nullable<System.DateTime> DateSubmittedField;
        
        private System.Nullable<decimal> DecimalScoreField;
        
        private System.Nullable<int> ExtraIntField;
        
        private string ExtraStringField;
        
        private System.Nullable<double> FloatScoreField;
        
        private int GameIDField;
        
        private System.Nullable<int> IntScoreField;
        
        private string PlayerNameField;
        
        private System.Nullable<int> RankField;
        
        private int ScoreIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSubmitted {
            get {
                return this.DateSubmittedField;
            }
            set {
                if ((this.DateSubmittedField.Equals(value) != true)) {
                    this.DateSubmittedField = value;
                    this.RaisePropertyChanged("DateSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DecimalScore {
            get {
                return this.DecimalScoreField;
            }
            set {
                if ((this.DecimalScoreField.Equals(value) != true)) {
                    this.DecimalScoreField = value;
                    this.RaisePropertyChanged("DecimalScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ExtraInt {
            get {
                return this.ExtraIntField;
            }
            set {
                if ((this.ExtraIntField.Equals(value) != true)) {
                    this.ExtraIntField = value;
                    this.RaisePropertyChanged("ExtraInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraString {
            get {
                return this.ExtraStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraStringField, value) != true)) {
                    this.ExtraStringField = value;
                    this.RaisePropertyChanged("ExtraString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> FloatScore {
            get {
                return this.FloatScoreField;
            }
            set {
                if ((this.FloatScoreField.Equals(value) != true)) {
                    this.FloatScoreField = value;
                    this.RaisePropertyChanged("FloatScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID {
            get {
                return this.GameIDField;
            }
            set {
                if ((this.GameIDField.Equals(value) != true)) {
                    this.GameIDField = value;
                    this.RaisePropertyChanged("GameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IntScore {
            get {
                return this.IntScoreField;
            }
            set {
                if ((this.IntScoreField.Equals(value) != true)) {
                    this.IntScoreField = value;
                    this.RaisePropertyChanged("IntScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScoreID {
            get {
                return this.ScoreIDField;
            }
            set {
                if ((this.ScoreIDField.Equals(value) != true)) {
                    this.ScoreIDField = value;
                    this.RaisePropertyChanged("ScoreID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LastWeek", Namespace="http://schemas.datacontract.org/2004/07/HighScoresService", IsReference=true)]
    public partial class LastWeek : HighScoresService.EntityObject {
        
        private System.Nullable<System.DateTime> DateSubmittedField;
        
        private System.Nullable<decimal> DecimalScoreField;
        
        private System.Nullable<int> ExtraIntField;
        
        private string ExtraStringField;
        
        private System.Nullable<double> FloatScoreField;
        
        private int GameIDField;
        
        private System.Nullable<int> IntScoreField;
        
        private string PlayerNameField;
        
        private System.Nullable<int> RankField;
        
        private int ScoreIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSubmitted {
            get {
                return this.DateSubmittedField;
            }
            set {
                if ((this.DateSubmittedField.Equals(value) != true)) {
                    this.DateSubmittedField = value;
                    this.RaisePropertyChanged("DateSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DecimalScore {
            get {
                return this.DecimalScoreField;
            }
            set {
                if ((this.DecimalScoreField.Equals(value) != true)) {
                    this.DecimalScoreField = value;
                    this.RaisePropertyChanged("DecimalScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ExtraInt {
            get {
                return this.ExtraIntField;
            }
            set {
                if ((this.ExtraIntField.Equals(value) != true)) {
                    this.ExtraIntField = value;
                    this.RaisePropertyChanged("ExtraInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraString {
            get {
                return this.ExtraStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraStringField, value) != true)) {
                    this.ExtraStringField = value;
                    this.RaisePropertyChanged("ExtraString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> FloatScore {
            get {
                return this.FloatScoreField;
            }
            set {
                if ((this.FloatScoreField.Equals(value) != true)) {
                    this.FloatScoreField = value;
                    this.RaisePropertyChanged("FloatScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID {
            get {
                return this.GameIDField;
            }
            set {
                if ((this.GameIDField.Equals(value) != true)) {
                    this.GameIDField = value;
                    this.RaisePropertyChanged("GameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IntScore {
            get {
                return this.IntScoreField;
            }
            set {
                if ((this.IntScoreField.Equals(value) != true)) {
                    this.IntScoreField = value;
                    this.RaisePropertyChanged("IntScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScoreID {
            get {
                return this.ScoreIDField;
            }
            set {
                if ((this.ScoreIDField.Equals(value) != true)) {
                    this.ScoreIDField = value;
                    this.RaisePropertyChanged("ScoreID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EntityContainerNameField;
        
        private System.Collections.ObjectModel.ObservableCollection<HighScoresService.EntityKeyMember> EntityKeyValuesField;
        
        private string EntitySetNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<HighScoresService.EntityKeyMember> EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<HighScoresService.EntityKeyMember>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<HighScoresService.Score>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.Score))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<HighScoresService.WeeklyScore>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.WeeklyScore))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<HighScoresService.LastWeek>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.LastWeek))]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string KeyField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HighScoresService.IHeroBashHighScores")]
    public interface IHeroBashHighScores {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroBashHighScores/GetNearbyScoresInGame", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetNearbyScoresInGameResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.Score>> GetNearbyScoresInGameAsync(int playthrough, int stage, float level, decimal time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroBashHighScores/GetNearbyScores", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetNearbyScoresResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.Score>> GetNearbyScoresAsync(int scoreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroBashHighScores/GetTopTenScores", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetTopTenScoresResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.Score>> GetTopTenScoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroBashHighScores/GetNearbyWeeklyScoresInGame", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetNearbyWeeklyScoresInGameResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.WeeklyScore>> GetNearbyWeeklyScoresInGameAsync(int playthrough, int stage, float level, decimal time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroBashHighScores/GetNearbyWeeklyScores", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetNearbyWeeklyScoresResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.WeeklyScore>> GetNearbyWeeklyScoresAsync(int scoreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroBashHighScores/GetTopTenWeeklyScores", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetTopTenWeeklyScoresResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.WeeklyScore>> GetTopTenWeeklyScoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroBashHighScores/GetLastWeekScore", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetLastWeekScoreResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.LastWeek>> GetLastWeekScoreAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroBashHighScores/GetMyPreviousScores", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetMyPreviousScoresResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.Score>> GetMyPreviousScoresAsync(string playerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroBashHighScores/AddScore", ReplyAction="http://tempuri.org/IHeroBashHighScores/AddScoreResponse")]
        System.Threading.Tasks.Task<int> AddScoreAsync(string playername, string playerid, int playthrough, int stage, float level, decimal time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroBashHighScores/AddWeeklyScore", ReplyAction="http://tempuri.org/IHeroBashHighScores/AddWeeklyScoreResponse")]
        System.Threading.Tasks.Task<int> AddWeeklyScoreAsync(string playername, string playerid, int playthrough, int stage, float level, decimal time);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHeroBashHighScoresChannel : HighScoresService.IHeroBashHighScores, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeroBashHighScoresClient : System.ServiceModel.ClientBase<HighScoresService.IHeroBashHighScores>, HighScoresService.IHeroBashHighScores {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HeroBashHighScoresClient() : 
                base(HeroBashHighScoresClient.GetDefaultBinding(), HeroBashHighScoresClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IHeroBashHighScores.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HeroBashHighScoresClient(EndpointConfiguration endpointConfiguration) : 
                base(HeroBashHighScoresClient.GetBindingForEndpoint(endpointConfiguration), HeroBashHighScoresClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HeroBashHighScoresClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HeroBashHighScoresClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HeroBashHighScoresClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HeroBashHighScoresClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HeroBashHighScoresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.Score>> GetNearbyScoresInGameAsync(int playthrough, int stage, float level, decimal time) {
            return base.Channel.GetNearbyScoresInGameAsync(playthrough, stage, level, time);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.Score>> GetNearbyScoresAsync(int scoreId) {
            return base.Channel.GetNearbyScoresAsync(scoreId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.Score>> GetTopTenScoresAsync() {
            return base.Channel.GetTopTenScoresAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.WeeklyScore>> GetNearbyWeeklyScoresInGameAsync(int playthrough, int stage, float level, decimal time) {
            return base.Channel.GetNearbyWeeklyScoresInGameAsync(playthrough, stage, level, time);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.WeeklyScore>> GetNearbyWeeklyScoresAsync(int scoreId) {
            return base.Channel.GetNearbyWeeklyScoresAsync(scoreId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.WeeklyScore>> GetTopTenWeeklyScoresAsync() {
            return base.Channel.GetTopTenWeeklyScoresAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.LastWeek>> GetLastWeekScoreAsync() {
            return base.Channel.GetLastWeekScoreAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<HighScoresService.Score>> GetMyPreviousScoresAsync(string playerid) {
            return base.Channel.GetMyPreviousScoresAsync(playerid);
        }
        
        public System.Threading.Tasks.Task<int> AddScoreAsync(string playername, string playerid, int playthrough, int stage, float level, decimal time) {
            return base.Channel.AddScoreAsync(playername, playerid, playthrough, stage, level, time);
        }
        
        public System.Threading.Tasks.Task<int> AddWeeklyScoreAsync(string playername, string playerid, int playthrough, int stage, float level, decimal time) {
            return base.Channel.AddWeeklyScoreAsync(playername, playerid, playthrough, stage, level, time);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHeroBashHighScores)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHeroBashHighScores)) {
                return new System.ServiceModel.EndpointAddress("http://highscores.team-mango.com/HeroBashHighScoresService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return HeroBashHighScoresClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IHeroBashHighScores);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return HeroBashHighScoresClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IHeroBashHighScores);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IHeroBashHighScores,
        }
    }
}
