//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace HeroBash.HighScoresService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Score", Namespace="http://schemas.datacontract.org/2004/07/HighScoresService", IsReference=true)]
    public partial class Score : HighScoresService.EntityObject {
        
        private System.Nullable<System.DateTime> DateSubmittedField;
        
        private System.Nullable<decimal> DecimalScoreField;
        
        private System.Nullable<int> ExtraIntField;
        
        private string ExtraStringField;
        
        private System.Nullable<double> FloatScoreField;
        
        private int GameIDField;
        
        private System.Nullable<int> IntScoreField;
        
        private string PlayerNameField;
        
        private System.Nullable<int> RankField;
        
        private int ScoreIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSubmitted {
            get {
                return this.DateSubmittedField;
            }
            set {
                if ((this.DateSubmittedField.Equals(value) != true)) {
                    this.DateSubmittedField = value;
                    this.RaisePropertyChanged("DateSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DecimalScore {
            get {
                return this.DecimalScoreField;
            }
            set {
                if ((this.DecimalScoreField.Equals(value) != true)) {
                    this.DecimalScoreField = value;
                    this.RaisePropertyChanged("DecimalScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ExtraInt {
            get {
                return this.ExtraIntField;
            }
            set {
                if ((this.ExtraIntField.Equals(value) != true)) {
                    this.ExtraIntField = value;
                    this.RaisePropertyChanged("ExtraInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraString {
            get {
                return this.ExtraStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraStringField, value) != true)) {
                    this.ExtraStringField = value;
                    this.RaisePropertyChanged("ExtraString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> FloatScore {
            get {
                return this.FloatScoreField;
            }
            set {
                if ((this.FloatScoreField.Equals(value) != true)) {
                    this.FloatScoreField = value;
                    this.RaisePropertyChanged("FloatScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID {
            get {
                return this.GameIDField;
            }
            set {
                if ((this.GameIDField.Equals(value) != true)) {
                    this.GameIDField = value;
                    this.RaisePropertyChanged("GameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IntScore {
            get {
                return this.IntScoreField;
            }
            set {
                if ((this.IntScoreField.Equals(value) != true)) {
                    this.IntScoreField = value;
                    this.RaisePropertyChanged("IntScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScoreID {
            get {
                return this.ScoreIDField;
            }
            set {
                if ((this.ScoreIDField.Equals(value) != true)) {
                    this.ScoreIDField = value;
                    this.RaisePropertyChanged("ScoreID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.WeeklyScore))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.LastWeek))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.Score))]
    public partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.WeeklyScore))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.LastWeek))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.Score))]
    public partial class EntityObject : HighScoresService.StructuralObject {
        
        private HighScoresService.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HighScoresService.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeeklyScore", Namespace="http://schemas.datacontract.org/2004/07/HighScoresService", IsReference=true)]
    public partial class WeeklyScore : HighScoresService.EntityObject {
        
        private System.Nullable<System.DateTime> DateSubmittedField;
        
        private System.Nullable<decimal> DecimalScoreField;
        
        private System.Nullable<int> ExtraIntField;
        
        private string ExtraStringField;
        
        private System.Nullable<double> FloatScoreField;
        
        private int GameIDField;
        
        private System.Nullable<int> IntScoreField;
        
        private string PlayerNameField;
        
        private System.Nullable<int> RankField;
        
        private int ScoreIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSubmitted {
            get {
                return this.DateSubmittedField;
            }
            set {
                if ((this.DateSubmittedField.Equals(value) != true)) {
                    this.DateSubmittedField = value;
                    this.RaisePropertyChanged("DateSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DecimalScore {
            get {
                return this.DecimalScoreField;
            }
            set {
                if ((this.DecimalScoreField.Equals(value) != true)) {
                    this.DecimalScoreField = value;
                    this.RaisePropertyChanged("DecimalScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ExtraInt {
            get {
                return this.ExtraIntField;
            }
            set {
                if ((this.ExtraIntField.Equals(value) != true)) {
                    this.ExtraIntField = value;
                    this.RaisePropertyChanged("ExtraInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraString {
            get {
                return this.ExtraStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraStringField, value) != true)) {
                    this.ExtraStringField = value;
                    this.RaisePropertyChanged("ExtraString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> FloatScore {
            get {
                return this.FloatScoreField;
            }
            set {
                if ((this.FloatScoreField.Equals(value) != true)) {
                    this.FloatScoreField = value;
                    this.RaisePropertyChanged("FloatScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID {
            get {
                return this.GameIDField;
            }
            set {
                if ((this.GameIDField.Equals(value) != true)) {
                    this.GameIDField = value;
                    this.RaisePropertyChanged("GameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IntScore {
            get {
                return this.IntScoreField;
            }
            set {
                if ((this.IntScoreField.Equals(value) != true)) {
                    this.IntScoreField = value;
                    this.RaisePropertyChanged("IntScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScoreID {
            get {
                return this.ScoreIDField;
            }
            set {
                if ((this.ScoreIDField.Equals(value) != true)) {
                    this.ScoreIDField = value;
                    this.RaisePropertyChanged("ScoreID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LastWeek", Namespace="http://schemas.datacontract.org/2004/07/HighScoresService", IsReference=true)]
    public partial class LastWeek : HighScoresService.EntityObject {
        
        private System.Nullable<System.DateTime> DateSubmittedField;
        
        private System.Nullable<decimal> DecimalScoreField;
        
        private System.Nullable<int> ExtraIntField;
        
        private string ExtraStringField;
        
        private System.Nullable<double> FloatScoreField;
        
        private int GameIDField;
        
        private System.Nullable<int> IntScoreField;
        
        private string PlayerNameField;
        
        private System.Nullable<int> RankField;
        
        private int ScoreIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSubmitted {
            get {
                return this.DateSubmittedField;
            }
            set {
                if ((this.DateSubmittedField.Equals(value) != true)) {
                    this.DateSubmittedField = value;
                    this.RaisePropertyChanged("DateSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DecimalScore {
            get {
                return this.DecimalScoreField;
            }
            set {
                if ((this.DecimalScoreField.Equals(value) != true)) {
                    this.DecimalScoreField = value;
                    this.RaisePropertyChanged("DecimalScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ExtraInt {
            get {
                return this.ExtraIntField;
            }
            set {
                if ((this.ExtraIntField.Equals(value) != true)) {
                    this.ExtraIntField = value;
                    this.RaisePropertyChanged("ExtraInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraString {
            get {
                return this.ExtraStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraStringField, value) != true)) {
                    this.ExtraStringField = value;
                    this.RaisePropertyChanged("ExtraString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> FloatScore {
            get {
                return this.FloatScoreField;
            }
            set {
                if ((this.FloatScoreField.Equals(value) != true)) {
                    this.FloatScoreField = value;
                    this.RaisePropertyChanged("FloatScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID {
            get {
                return this.GameIDField;
            }
            set {
                if ((this.GameIDField.Equals(value) != true)) {
                    this.GameIDField = value;
                    this.RaisePropertyChanged("GameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IntScore {
            get {
                return this.IntScoreField;
            }
            set {
                if ((this.IntScoreField.Equals(value) != true)) {
                    this.IntScoreField = value;
                    this.RaisePropertyChanged("IntScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScoreID {
            get {
                return this.ScoreIDField;
            }
            set {
                if ((this.ScoreIDField.Equals(value) != true)) {
                    this.ScoreIDField = value;
                    this.RaisePropertyChanged("ScoreID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EntityContainerNameField;
        
        private HighScoresService.EntityKeyMember[] EntityKeyValuesField;
        
        private string EntitySetNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HighScoresService.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.Score[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.Score))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.WeeklyScore[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.WeeklyScore))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.LastWeek[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HighScoresService.LastWeek))]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string KeyField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HighScoresService.IHeroBashHighScores")]
    public interface IHeroBashHighScores {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHeroBashHighScores/GetNearbyScoresInGame", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetNearbyScoresInGameResponse")]
        System.IAsyncResult BeginGetNearbyScoresInGame(int playthrough, int stage, float level, decimal time, System.AsyncCallback callback, object asyncState);
        
        HighScoresService.Score[] EndGetNearbyScoresInGame(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHeroBashHighScores/GetNearbyScores", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetNearbyScoresResponse")]
        System.IAsyncResult BeginGetNearbyScores(int scoreId, System.AsyncCallback callback, object asyncState);
        
        HighScoresService.Score[] EndGetNearbyScores(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHeroBashHighScores/GetTopTenScores", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetTopTenScoresResponse")]
        System.IAsyncResult BeginGetTopTenScores(System.AsyncCallback callback, object asyncState);
        
        HighScoresService.Score[] EndGetTopTenScores(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHeroBashHighScores/GetNearbyWeeklyScoresInGame", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetNearbyWeeklyScoresInGameResponse")]
        System.IAsyncResult BeginGetNearbyWeeklyScoresInGame(int playthrough, int stage, float level, decimal time, System.AsyncCallback callback, object asyncState);
        
        HighScoresService.WeeklyScore[] EndGetNearbyWeeklyScoresInGame(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHeroBashHighScores/GetNearbyWeeklyScores", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetNearbyWeeklyScoresResponse")]
        System.IAsyncResult BeginGetNearbyWeeklyScores(int scoreId, System.AsyncCallback callback, object asyncState);
        
        HighScoresService.WeeklyScore[] EndGetNearbyWeeklyScores(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHeroBashHighScores/GetTopTenWeeklyScores", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetTopTenWeeklyScoresResponse")]
        System.IAsyncResult BeginGetTopTenWeeklyScores(System.AsyncCallback callback, object asyncState);
        
        HighScoresService.WeeklyScore[] EndGetTopTenWeeklyScores(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHeroBashHighScores/GetLastWeekScore", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetLastWeekScoreResponse")]
        System.IAsyncResult BeginGetLastWeekScore(System.AsyncCallback callback, object asyncState);
        
        HighScoresService.LastWeek[] EndGetLastWeekScore(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHeroBashHighScores/GetMyPreviousScores", ReplyAction="http://tempuri.org/IHeroBashHighScores/GetMyPreviousScoresResponse")]
        System.IAsyncResult BeginGetMyPreviousScores(string playerid, System.AsyncCallback callback, object asyncState);
        
        HighScoresService.Score[] EndGetMyPreviousScores(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHeroBashHighScores/AddScore", ReplyAction="http://tempuri.org/IHeroBashHighScores/AddScoreResponse")]
        System.IAsyncResult BeginAddScore(string playername, string playerid, int playthrough, int stage, float level, decimal time, System.AsyncCallback callback, object asyncState);
        
        int EndAddScore(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHeroBashHighScores/AddWeeklyScore", ReplyAction="http://tempuri.org/IHeroBashHighScores/AddWeeklyScoreResponse")]
        System.IAsyncResult BeginAddWeeklyScore(string playername, string playerid, int playthrough, int stage, float level, decimal time, System.AsyncCallback callback, object asyncState);
        
        int EndAddWeeklyScore(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHeroBashHighScoresChannel : HighScoresService.IHeroBashHighScores, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNearbyScoresInGameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNearbyScoresInGameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HighScoresService.Score[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HighScoresService.Score[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNearbyScoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNearbyScoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HighScoresService.Score[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HighScoresService.Score[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTopTenScoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTopTenScoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HighScoresService.Score[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HighScoresService.Score[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNearbyWeeklyScoresInGameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNearbyWeeklyScoresInGameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HighScoresService.WeeklyScore[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HighScoresService.WeeklyScore[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNearbyWeeklyScoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNearbyWeeklyScoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HighScoresService.WeeklyScore[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HighScoresService.WeeklyScore[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTopTenWeeklyScoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTopTenWeeklyScoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HighScoresService.WeeklyScore[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HighScoresService.WeeklyScore[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLastWeekScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLastWeekScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HighScoresService.LastWeek[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HighScoresService.LastWeek[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMyPreviousScoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMyPreviousScoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HighScoresService.Score[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HighScoresService.Score[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddWeeklyScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddWeeklyScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeroBashHighScoresClient : System.ServiceModel.ClientBase<HighScoresService.IHeroBashHighScores>, HighScoresService.IHeroBashHighScores {
        
        private BeginOperationDelegate onBeginGetNearbyScoresInGameDelegate;
        
        private EndOperationDelegate onEndGetNearbyScoresInGameDelegate;
        
        private System.Threading.SendOrPostCallback onGetNearbyScoresInGameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNearbyScoresDelegate;
        
        private EndOperationDelegate onEndGetNearbyScoresDelegate;
        
        private System.Threading.SendOrPostCallback onGetNearbyScoresCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTopTenScoresDelegate;
        
        private EndOperationDelegate onEndGetTopTenScoresDelegate;
        
        private System.Threading.SendOrPostCallback onGetTopTenScoresCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNearbyWeeklyScoresInGameDelegate;
        
        private EndOperationDelegate onEndGetNearbyWeeklyScoresInGameDelegate;
        
        private System.Threading.SendOrPostCallback onGetNearbyWeeklyScoresInGameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNearbyWeeklyScoresDelegate;
        
        private EndOperationDelegate onEndGetNearbyWeeklyScoresDelegate;
        
        private System.Threading.SendOrPostCallback onGetNearbyWeeklyScoresCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTopTenWeeklyScoresDelegate;
        
        private EndOperationDelegate onEndGetTopTenWeeklyScoresDelegate;
        
        private System.Threading.SendOrPostCallback onGetTopTenWeeklyScoresCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLastWeekScoreDelegate;
        
        private EndOperationDelegate onEndGetLastWeekScoreDelegate;
        
        private System.Threading.SendOrPostCallback onGetLastWeekScoreCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMyPreviousScoresDelegate;
        
        private EndOperationDelegate onEndGetMyPreviousScoresDelegate;
        
        private System.Threading.SendOrPostCallback onGetMyPreviousScoresCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddScoreDelegate;
        
        private EndOperationDelegate onEndAddScoreDelegate;
        
        private System.Threading.SendOrPostCallback onAddScoreCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddWeeklyScoreDelegate;
        
        private EndOperationDelegate onEndAddWeeklyScoreDelegate;
        
        private System.Threading.SendOrPostCallback onAddWeeklyScoreCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public HeroBashHighScoresClient() {
        }
        
        public HeroBashHighScoresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HeroBashHighScoresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeroBashHighScoresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeroBashHighScoresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetNearbyScoresInGameCompletedEventArgs> GetNearbyScoresInGameCompleted;
        
        public event System.EventHandler<GetNearbyScoresCompletedEventArgs> GetNearbyScoresCompleted;
        
        public event System.EventHandler<GetTopTenScoresCompletedEventArgs> GetTopTenScoresCompleted;
        
        public event System.EventHandler<GetNearbyWeeklyScoresInGameCompletedEventArgs> GetNearbyWeeklyScoresInGameCompleted;
        
        public event System.EventHandler<GetNearbyWeeklyScoresCompletedEventArgs> GetNearbyWeeklyScoresCompleted;
        
        public event System.EventHandler<GetTopTenWeeklyScoresCompletedEventArgs> GetTopTenWeeklyScoresCompleted;
        
        public event System.EventHandler<GetLastWeekScoreCompletedEventArgs> GetLastWeekScoreCompleted;
        
        public event System.EventHandler<GetMyPreviousScoresCompletedEventArgs> GetMyPreviousScoresCompleted;
        
        public event System.EventHandler<AddScoreCompletedEventArgs> AddScoreCompleted;
        
        public event System.EventHandler<AddWeeklyScoreCompletedEventArgs> AddWeeklyScoreCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HighScoresService.IHeroBashHighScores.BeginGetNearbyScoresInGame(int playthrough, int stage, float level, decimal time, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNearbyScoresInGame(playthrough, stage, level, time, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HighScoresService.Score[] HighScoresService.IHeroBashHighScores.EndGetNearbyScoresInGame(System.IAsyncResult result) {
            return base.Channel.EndGetNearbyScoresInGame(result);
        }
        
        private System.IAsyncResult OnBeginGetNearbyScoresInGame(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int playthrough = ((int)(inValues[0]));
            int stage = ((int)(inValues[1]));
            float level = ((float)(inValues[2]));
            decimal time = ((decimal)(inValues[3]));
            return ((HighScoresService.IHeroBashHighScores)(this)).BeginGetNearbyScoresInGame(playthrough, stage, level, time, callback, asyncState);
        }
        
        private object[] OnEndGetNearbyScoresInGame(System.IAsyncResult result) {
            HighScoresService.Score[] retVal = ((HighScoresService.IHeroBashHighScores)(this)).EndGetNearbyScoresInGame(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNearbyScoresInGameCompleted(object state) {
            if ((this.GetNearbyScoresInGameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNearbyScoresInGameCompleted(this, new GetNearbyScoresInGameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNearbyScoresInGameAsync(int playthrough, int stage, float level, decimal time) {
            this.GetNearbyScoresInGameAsync(playthrough, stage, level, time, null);
        }
        
        public void GetNearbyScoresInGameAsync(int playthrough, int stage, float level, decimal time, object userState) {
            if ((this.onBeginGetNearbyScoresInGameDelegate == null)) {
                this.onBeginGetNearbyScoresInGameDelegate = new BeginOperationDelegate(this.OnBeginGetNearbyScoresInGame);
            }
            if ((this.onEndGetNearbyScoresInGameDelegate == null)) {
                this.onEndGetNearbyScoresInGameDelegate = new EndOperationDelegate(this.OnEndGetNearbyScoresInGame);
            }
            if ((this.onGetNearbyScoresInGameCompletedDelegate == null)) {
                this.onGetNearbyScoresInGameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNearbyScoresInGameCompleted);
            }
            base.InvokeAsync(this.onBeginGetNearbyScoresInGameDelegate, new object[] {
                        playthrough,
                        stage,
                        level,
                        time}, this.onEndGetNearbyScoresInGameDelegate, this.onGetNearbyScoresInGameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HighScoresService.IHeroBashHighScores.BeginGetNearbyScores(int scoreId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNearbyScores(scoreId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HighScoresService.Score[] HighScoresService.IHeroBashHighScores.EndGetNearbyScores(System.IAsyncResult result) {
            return base.Channel.EndGetNearbyScores(result);
        }
        
        private System.IAsyncResult OnBeginGetNearbyScores(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int scoreId = ((int)(inValues[0]));
            return ((HighScoresService.IHeroBashHighScores)(this)).BeginGetNearbyScores(scoreId, callback, asyncState);
        }
        
        private object[] OnEndGetNearbyScores(System.IAsyncResult result) {
            HighScoresService.Score[] retVal = ((HighScoresService.IHeroBashHighScores)(this)).EndGetNearbyScores(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNearbyScoresCompleted(object state) {
            if ((this.GetNearbyScoresCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNearbyScoresCompleted(this, new GetNearbyScoresCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNearbyScoresAsync(int scoreId) {
            this.GetNearbyScoresAsync(scoreId, null);
        }
        
        public void GetNearbyScoresAsync(int scoreId, object userState) {
            if ((this.onBeginGetNearbyScoresDelegate == null)) {
                this.onBeginGetNearbyScoresDelegate = new BeginOperationDelegate(this.OnBeginGetNearbyScores);
            }
            if ((this.onEndGetNearbyScoresDelegate == null)) {
                this.onEndGetNearbyScoresDelegate = new EndOperationDelegate(this.OnEndGetNearbyScores);
            }
            if ((this.onGetNearbyScoresCompletedDelegate == null)) {
                this.onGetNearbyScoresCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNearbyScoresCompleted);
            }
            base.InvokeAsync(this.onBeginGetNearbyScoresDelegate, new object[] {
                        scoreId}, this.onEndGetNearbyScoresDelegate, this.onGetNearbyScoresCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HighScoresService.IHeroBashHighScores.BeginGetTopTenScores(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTopTenScores(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HighScoresService.Score[] HighScoresService.IHeroBashHighScores.EndGetTopTenScores(System.IAsyncResult result) {
            return base.Channel.EndGetTopTenScores(result);
        }
        
        private System.IAsyncResult OnBeginGetTopTenScores(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((HighScoresService.IHeroBashHighScores)(this)).BeginGetTopTenScores(callback, asyncState);
        }
        
        private object[] OnEndGetTopTenScores(System.IAsyncResult result) {
            HighScoresService.Score[] retVal = ((HighScoresService.IHeroBashHighScores)(this)).EndGetTopTenScores(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTopTenScoresCompleted(object state) {
            if ((this.GetTopTenScoresCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTopTenScoresCompleted(this, new GetTopTenScoresCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTopTenScoresAsync() {
            this.GetTopTenScoresAsync(null);
        }
        
        public void GetTopTenScoresAsync(object userState) {
            if ((this.onBeginGetTopTenScoresDelegate == null)) {
                this.onBeginGetTopTenScoresDelegate = new BeginOperationDelegate(this.OnBeginGetTopTenScores);
            }
            if ((this.onEndGetTopTenScoresDelegate == null)) {
                this.onEndGetTopTenScoresDelegate = new EndOperationDelegate(this.OnEndGetTopTenScores);
            }
            if ((this.onGetTopTenScoresCompletedDelegate == null)) {
                this.onGetTopTenScoresCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTopTenScoresCompleted);
            }
            base.InvokeAsync(this.onBeginGetTopTenScoresDelegate, null, this.onEndGetTopTenScoresDelegate, this.onGetTopTenScoresCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HighScoresService.IHeroBashHighScores.BeginGetNearbyWeeklyScoresInGame(int playthrough, int stage, float level, decimal time, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNearbyWeeklyScoresInGame(playthrough, stage, level, time, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HighScoresService.WeeklyScore[] HighScoresService.IHeroBashHighScores.EndGetNearbyWeeklyScoresInGame(System.IAsyncResult result) {
            return base.Channel.EndGetNearbyWeeklyScoresInGame(result);
        }
        
        private System.IAsyncResult OnBeginGetNearbyWeeklyScoresInGame(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int playthrough = ((int)(inValues[0]));
            int stage = ((int)(inValues[1]));
            float level = ((float)(inValues[2]));
            decimal time = ((decimal)(inValues[3]));
            return ((HighScoresService.IHeroBashHighScores)(this)).BeginGetNearbyWeeklyScoresInGame(playthrough, stage, level, time, callback, asyncState);
        }
        
        private object[] OnEndGetNearbyWeeklyScoresInGame(System.IAsyncResult result) {
            HighScoresService.WeeklyScore[] retVal = ((HighScoresService.IHeroBashHighScores)(this)).EndGetNearbyWeeklyScoresInGame(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNearbyWeeklyScoresInGameCompleted(object state) {
            if ((this.GetNearbyWeeklyScoresInGameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNearbyWeeklyScoresInGameCompleted(this, new GetNearbyWeeklyScoresInGameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNearbyWeeklyScoresInGameAsync(int playthrough, int stage, float level, decimal time) {
            this.GetNearbyWeeklyScoresInGameAsync(playthrough, stage, level, time, null);
        }
        
        public void GetNearbyWeeklyScoresInGameAsync(int playthrough, int stage, float level, decimal time, object userState) {
            if ((this.onBeginGetNearbyWeeklyScoresInGameDelegate == null)) {
                this.onBeginGetNearbyWeeklyScoresInGameDelegate = new BeginOperationDelegate(this.OnBeginGetNearbyWeeklyScoresInGame);
            }
            if ((this.onEndGetNearbyWeeklyScoresInGameDelegate == null)) {
                this.onEndGetNearbyWeeklyScoresInGameDelegate = new EndOperationDelegate(this.OnEndGetNearbyWeeklyScoresInGame);
            }
            if ((this.onGetNearbyWeeklyScoresInGameCompletedDelegate == null)) {
                this.onGetNearbyWeeklyScoresInGameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNearbyWeeklyScoresInGameCompleted);
            }
            base.InvokeAsync(this.onBeginGetNearbyWeeklyScoresInGameDelegate, new object[] {
                        playthrough,
                        stage,
                        level,
                        time}, this.onEndGetNearbyWeeklyScoresInGameDelegate, this.onGetNearbyWeeklyScoresInGameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HighScoresService.IHeroBashHighScores.BeginGetNearbyWeeklyScores(int scoreId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNearbyWeeklyScores(scoreId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HighScoresService.WeeklyScore[] HighScoresService.IHeroBashHighScores.EndGetNearbyWeeklyScores(System.IAsyncResult result) {
            return base.Channel.EndGetNearbyWeeklyScores(result);
        }
        
        private System.IAsyncResult OnBeginGetNearbyWeeklyScores(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int scoreId = ((int)(inValues[0]));
            return ((HighScoresService.IHeroBashHighScores)(this)).BeginGetNearbyWeeklyScores(scoreId, callback, asyncState);
        }
        
        private object[] OnEndGetNearbyWeeklyScores(System.IAsyncResult result) {
            HighScoresService.WeeklyScore[] retVal = ((HighScoresService.IHeroBashHighScores)(this)).EndGetNearbyWeeklyScores(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNearbyWeeklyScoresCompleted(object state) {
            if ((this.GetNearbyWeeklyScoresCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNearbyWeeklyScoresCompleted(this, new GetNearbyWeeklyScoresCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNearbyWeeklyScoresAsync(int scoreId) {
            this.GetNearbyWeeklyScoresAsync(scoreId, null);
        }
        
        public void GetNearbyWeeklyScoresAsync(int scoreId, object userState) {
            if ((this.onBeginGetNearbyWeeklyScoresDelegate == null)) {
                this.onBeginGetNearbyWeeklyScoresDelegate = new BeginOperationDelegate(this.OnBeginGetNearbyWeeklyScores);
            }
            if ((this.onEndGetNearbyWeeklyScoresDelegate == null)) {
                this.onEndGetNearbyWeeklyScoresDelegate = new EndOperationDelegate(this.OnEndGetNearbyWeeklyScores);
            }
            if ((this.onGetNearbyWeeklyScoresCompletedDelegate == null)) {
                this.onGetNearbyWeeklyScoresCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNearbyWeeklyScoresCompleted);
            }
            base.InvokeAsync(this.onBeginGetNearbyWeeklyScoresDelegate, new object[] {
                        scoreId}, this.onEndGetNearbyWeeklyScoresDelegate, this.onGetNearbyWeeklyScoresCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HighScoresService.IHeroBashHighScores.BeginGetTopTenWeeklyScores(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTopTenWeeklyScores(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HighScoresService.WeeklyScore[] HighScoresService.IHeroBashHighScores.EndGetTopTenWeeklyScores(System.IAsyncResult result) {
            return base.Channel.EndGetTopTenWeeklyScores(result);
        }
        
        private System.IAsyncResult OnBeginGetTopTenWeeklyScores(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((HighScoresService.IHeroBashHighScores)(this)).BeginGetTopTenWeeklyScores(callback, asyncState);
        }
        
        private object[] OnEndGetTopTenWeeklyScores(System.IAsyncResult result) {
            HighScoresService.WeeklyScore[] retVal = ((HighScoresService.IHeroBashHighScores)(this)).EndGetTopTenWeeklyScores(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTopTenWeeklyScoresCompleted(object state) {
            if ((this.GetTopTenWeeklyScoresCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTopTenWeeklyScoresCompleted(this, new GetTopTenWeeklyScoresCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTopTenWeeklyScoresAsync() {
            this.GetTopTenWeeklyScoresAsync(null);
        }
        
        public void GetTopTenWeeklyScoresAsync(object userState) {
            if ((this.onBeginGetTopTenWeeklyScoresDelegate == null)) {
                this.onBeginGetTopTenWeeklyScoresDelegate = new BeginOperationDelegate(this.OnBeginGetTopTenWeeklyScores);
            }
            if ((this.onEndGetTopTenWeeklyScoresDelegate == null)) {
                this.onEndGetTopTenWeeklyScoresDelegate = new EndOperationDelegate(this.OnEndGetTopTenWeeklyScores);
            }
            if ((this.onGetTopTenWeeklyScoresCompletedDelegate == null)) {
                this.onGetTopTenWeeklyScoresCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTopTenWeeklyScoresCompleted);
            }
            base.InvokeAsync(this.onBeginGetTopTenWeeklyScoresDelegate, null, this.onEndGetTopTenWeeklyScoresDelegate, this.onGetTopTenWeeklyScoresCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HighScoresService.IHeroBashHighScores.BeginGetLastWeekScore(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLastWeekScore(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HighScoresService.LastWeek[] HighScoresService.IHeroBashHighScores.EndGetLastWeekScore(System.IAsyncResult result) {
            return base.Channel.EndGetLastWeekScore(result);
        }
        
        private System.IAsyncResult OnBeginGetLastWeekScore(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((HighScoresService.IHeroBashHighScores)(this)).BeginGetLastWeekScore(callback, asyncState);
        }
        
        private object[] OnEndGetLastWeekScore(System.IAsyncResult result) {
            HighScoresService.LastWeek[] retVal = ((HighScoresService.IHeroBashHighScores)(this)).EndGetLastWeekScore(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLastWeekScoreCompleted(object state) {
            if ((this.GetLastWeekScoreCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLastWeekScoreCompleted(this, new GetLastWeekScoreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLastWeekScoreAsync() {
            this.GetLastWeekScoreAsync(null);
        }
        
        public void GetLastWeekScoreAsync(object userState) {
            if ((this.onBeginGetLastWeekScoreDelegate == null)) {
                this.onBeginGetLastWeekScoreDelegate = new BeginOperationDelegate(this.OnBeginGetLastWeekScore);
            }
            if ((this.onEndGetLastWeekScoreDelegate == null)) {
                this.onEndGetLastWeekScoreDelegate = new EndOperationDelegate(this.OnEndGetLastWeekScore);
            }
            if ((this.onGetLastWeekScoreCompletedDelegate == null)) {
                this.onGetLastWeekScoreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLastWeekScoreCompleted);
            }
            base.InvokeAsync(this.onBeginGetLastWeekScoreDelegate, null, this.onEndGetLastWeekScoreDelegate, this.onGetLastWeekScoreCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HighScoresService.IHeroBashHighScores.BeginGetMyPreviousScores(string playerid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMyPreviousScores(playerid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HighScoresService.Score[] HighScoresService.IHeroBashHighScores.EndGetMyPreviousScores(System.IAsyncResult result) {
            return base.Channel.EndGetMyPreviousScores(result);
        }
        
        private System.IAsyncResult OnBeginGetMyPreviousScores(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string playerid = ((string)(inValues[0]));
            return ((HighScoresService.IHeroBashHighScores)(this)).BeginGetMyPreviousScores(playerid, callback, asyncState);
        }
        
        private object[] OnEndGetMyPreviousScores(System.IAsyncResult result) {
            HighScoresService.Score[] retVal = ((HighScoresService.IHeroBashHighScores)(this)).EndGetMyPreviousScores(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMyPreviousScoresCompleted(object state) {
            if ((this.GetMyPreviousScoresCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMyPreviousScoresCompleted(this, new GetMyPreviousScoresCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMyPreviousScoresAsync(string playerid) {
            this.GetMyPreviousScoresAsync(playerid, null);
        }
        
        public void GetMyPreviousScoresAsync(string playerid, object userState) {
            if ((this.onBeginGetMyPreviousScoresDelegate == null)) {
                this.onBeginGetMyPreviousScoresDelegate = new BeginOperationDelegate(this.OnBeginGetMyPreviousScores);
            }
            if ((this.onEndGetMyPreviousScoresDelegate == null)) {
                this.onEndGetMyPreviousScoresDelegate = new EndOperationDelegate(this.OnEndGetMyPreviousScores);
            }
            if ((this.onGetMyPreviousScoresCompletedDelegate == null)) {
                this.onGetMyPreviousScoresCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMyPreviousScoresCompleted);
            }
            base.InvokeAsync(this.onBeginGetMyPreviousScoresDelegate, new object[] {
                        playerid}, this.onEndGetMyPreviousScoresDelegate, this.onGetMyPreviousScoresCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HighScoresService.IHeroBashHighScores.BeginAddScore(string playername, string playerid, int playthrough, int stage, float level, decimal time, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddScore(playername, playerid, playthrough, stage, level, time, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int HighScoresService.IHeroBashHighScores.EndAddScore(System.IAsyncResult result) {
            return base.Channel.EndAddScore(result);
        }
        
        private System.IAsyncResult OnBeginAddScore(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string playername = ((string)(inValues[0]));
            string playerid = ((string)(inValues[1]));
            int playthrough = ((int)(inValues[2]));
            int stage = ((int)(inValues[3]));
            float level = ((float)(inValues[4]));
            decimal time = ((decimal)(inValues[5]));
            return ((HighScoresService.IHeroBashHighScores)(this)).BeginAddScore(playername, playerid, playthrough, stage, level, time, callback, asyncState);
        }
        
        private object[] OnEndAddScore(System.IAsyncResult result) {
            int retVal = ((HighScoresService.IHeroBashHighScores)(this)).EndAddScore(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddScoreCompleted(object state) {
            if ((this.AddScoreCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddScoreCompleted(this, new AddScoreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddScoreAsync(string playername, string playerid, int playthrough, int stage, float level, decimal time) {
            this.AddScoreAsync(playername, playerid, playthrough, stage, level, time, null);
        }
        
        public void AddScoreAsync(string playername, string playerid, int playthrough, int stage, float level, decimal time, object userState) {
            if ((this.onBeginAddScoreDelegate == null)) {
                this.onBeginAddScoreDelegate = new BeginOperationDelegate(this.OnBeginAddScore);
            }
            if ((this.onEndAddScoreDelegate == null)) {
                this.onEndAddScoreDelegate = new EndOperationDelegate(this.OnEndAddScore);
            }
            if ((this.onAddScoreCompletedDelegate == null)) {
                this.onAddScoreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddScoreCompleted);
            }
            base.InvokeAsync(this.onBeginAddScoreDelegate, new object[] {
                        playername,
                        playerid,
                        playthrough,
                        stage,
                        level,
                        time}, this.onEndAddScoreDelegate, this.onAddScoreCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HighScoresService.IHeroBashHighScores.BeginAddWeeklyScore(string playername, string playerid, int playthrough, int stage, float level, decimal time, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddWeeklyScore(playername, playerid, playthrough, stage, level, time, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int HighScoresService.IHeroBashHighScores.EndAddWeeklyScore(System.IAsyncResult result) {
            return base.Channel.EndAddWeeklyScore(result);
        }
        
        private System.IAsyncResult OnBeginAddWeeklyScore(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string playername = ((string)(inValues[0]));
            string playerid = ((string)(inValues[1]));
            int playthrough = ((int)(inValues[2]));
            int stage = ((int)(inValues[3]));
            float level = ((float)(inValues[4]));
            decimal time = ((decimal)(inValues[5]));
            return ((HighScoresService.IHeroBashHighScores)(this)).BeginAddWeeklyScore(playername, playerid, playthrough, stage, level, time, callback, asyncState);
        }
        
        private object[] OnEndAddWeeklyScore(System.IAsyncResult result) {
            int retVal = ((HighScoresService.IHeroBashHighScores)(this)).EndAddWeeklyScore(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddWeeklyScoreCompleted(object state) {
            if ((this.AddWeeklyScoreCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddWeeklyScoreCompleted(this, new AddWeeklyScoreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddWeeklyScoreAsync(string playername, string playerid, int playthrough, int stage, float level, decimal time) {
            this.AddWeeklyScoreAsync(playername, playerid, playthrough, stage, level, time, null);
        }
        
        public void AddWeeklyScoreAsync(string playername, string playerid, int playthrough, int stage, float level, decimal time, object userState) {
            if ((this.onBeginAddWeeklyScoreDelegate == null)) {
                this.onBeginAddWeeklyScoreDelegate = new BeginOperationDelegate(this.OnBeginAddWeeklyScore);
            }
            if ((this.onEndAddWeeklyScoreDelegate == null)) {
                this.onEndAddWeeklyScoreDelegate = new EndOperationDelegate(this.OnEndAddWeeklyScore);
            }
            if ((this.onAddWeeklyScoreCompletedDelegate == null)) {
                this.onAddWeeklyScoreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddWeeklyScoreCompleted);
            }
            base.InvokeAsync(this.onBeginAddWeeklyScoreDelegate, new object[] {
                        playername,
                        playerid,
                        playthrough,
                        stage,
                        level,
                        time}, this.onEndAddWeeklyScoreDelegate, this.onAddWeeklyScoreCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override HighScoresService.IHeroBashHighScores CreateChannel() {
            return new HeroBashHighScoresClientChannel(this);
        }
        
        private class HeroBashHighScoresClientChannel : ChannelBase<HighScoresService.IHeroBashHighScores>, HighScoresService.IHeroBashHighScores {
            
            public HeroBashHighScoresClientChannel(System.ServiceModel.ClientBase<HighScoresService.IHeroBashHighScores> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetNearbyScoresInGame(int playthrough, int stage, float level, decimal time, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = playthrough;
                _args[1] = stage;
                _args[2] = level;
                _args[3] = time;
                System.IAsyncResult _result = base.BeginInvoke("GetNearbyScoresInGame", _args, callback, asyncState);
                return _result;
            }
            
            public HighScoresService.Score[] EndGetNearbyScoresInGame(System.IAsyncResult result) {
                object[] _args = new object[0];
                HighScoresService.Score[] _result = ((HighScoresService.Score[])(base.EndInvoke("GetNearbyScoresInGame", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetNearbyScores(int scoreId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = scoreId;
                System.IAsyncResult _result = base.BeginInvoke("GetNearbyScores", _args, callback, asyncState);
                return _result;
            }
            
            public HighScoresService.Score[] EndGetNearbyScores(System.IAsyncResult result) {
                object[] _args = new object[0];
                HighScoresService.Score[] _result = ((HighScoresService.Score[])(base.EndInvoke("GetNearbyScores", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTopTenScores(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTopTenScores", _args, callback, asyncState);
                return _result;
            }
            
            public HighScoresService.Score[] EndGetTopTenScores(System.IAsyncResult result) {
                object[] _args = new object[0];
                HighScoresService.Score[] _result = ((HighScoresService.Score[])(base.EndInvoke("GetTopTenScores", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetNearbyWeeklyScoresInGame(int playthrough, int stage, float level, decimal time, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = playthrough;
                _args[1] = stage;
                _args[2] = level;
                _args[3] = time;
                System.IAsyncResult _result = base.BeginInvoke("GetNearbyWeeklyScoresInGame", _args, callback, asyncState);
                return _result;
            }
            
            public HighScoresService.WeeklyScore[] EndGetNearbyWeeklyScoresInGame(System.IAsyncResult result) {
                object[] _args = new object[0];
                HighScoresService.WeeklyScore[] _result = ((HighScoresService.WeeklyScore[])(base.EndInvoke("GetNearbyWeeklyScoresInGame", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetNearbyWeeklyScores(int scoreId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = scoreId;
                System.IAsyncResult _result = base.BeginInvoke("GetNearbyWeeklyScores", _args, callback, asyncState);
                return _result;
            }
            
            public HighScoresService.WeeklyScore[] EndGetNearbyWeeklyScores(System.IAsyncResult result) {
                object[] _args = new object[0];
                HighScoresService.WeeklyScore[] _result = ((HighScoresService.WeeklyScore[])(base.EndInvoke("GetNearbyWeeklyScores", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTopTenWeeklyScores(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTopTenWeeklyScores", _args, callback, asyncState);
                return _result;
            }
            
            public HighScoresService.WeeklyScore[] EndGetTopTenWeeklyScores(System.IAsyncResult result) {
                object[] _args = new object[0];
                HighScoresService.WeeklyScore[] _result = ((HighScoresService.WeeklyScore[])(base.EndInvoke("GetTopTenWeeklyScores", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLastWeekScore(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetLastWeekScore", _args, callback, asyncState);
                return _result;
            }
            
            public HighScoresService.LastWeek[] EndGetLastWeekScore(System.IAsyncResult result) {
                object[] _args = new object[0];
                HighScoresService.LastWeek[] _result = ((HighScoresService.LastWeek[])(base.EndInvoke("GetLastWeekScore", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMyPreviousScores(string playerid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = playerid;
                System.IAsyncResult _result = base.BeginInvoke("GetMyPreviousScores", _args, callback, asyncState);
                return _result;
            }
            
            public HighScoresService.Score[] EndGetMyPreviousScores(System.IAsyncResult result) {
                object[] _args = new object[0];
                HighScoresService.Score[] _result = ((HighScoresService.Score[])(base.EndInvoke("GetMyPreviousScores", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddScore(string playername, string playerid, int playthrough, int stage, float level, decimal time, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = playername;
                _args[1] = playerid;
                _args[2] = playthrough;
                _args[3] = stage;
                _args[4] = level;
                _args[5] = time;
                System.IAsyncResult _result = base.BeginInvoke("AddScore", _args, callback, asyncState);
                return _result;
            }
            
            public int EndAddScore(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("AddScore", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddWeeklyScore(string playername, string playerid, int playthrough, int stage, float level, decimal time, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = playername;
                _args[1] = playerid;
                _args[2] = playthrough;
                _args[3] = stage;
                _args[4] = level;
                _args[5] = time;
                System.IAsyncResult _result = base.BeginInvoke("AddWeeklyScore", _args, callback, asyncState);
                return _result;
            }
            
            public int EndAddWeeklyScore(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("AddWeeklyScore", _args, result)));
                return _result;
            }
        }
    }
}
